language: erlang
notifications:
  email: ruan800@gmail.cmo
otp_release:
  # - R15B
  # - R15B01
  # - R15B03
  # - R16B03-1
  # - 17.3
  # - 17.5
  - 18.0
  - 18.3
  - 19.0
script: rebar clean compile eunit skip_deps=true
env:
  global:
    - TIMEOUT=100

