language: erlang

notifications:
  email: ruan800@gmail.com

before_script:
  kerl list installations

otp_release:
    - 21.3
    - 21.3.8.24
    - 22.3
    - 22.3.4.26
    - 23.3
    - 23.3.4.18
    - 24.3
    - 24.3.4.6
    - 25.1

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

script:
  epmd -daemon && make && ./rebar3 eunit -v -c && ./rebar3 ct -c --readable true --verbose && ./rebar3 cover -v && ./rebar3 coveralls send

env:
  global:
    - TIMEOUT=100

dist: trusty

