language: erlang
notifications:
  email: ruan800@gmail.com
before_script:
  kerl list installations
otp_release:
  - 17.5
  - 18.2
  - 19.2
script:
  rebar clean && rebar compile && rebar skip_deps=true eunit && rebar skip_deps=true ct
env:
  global:
    - TIMEOUT=100

