language: erlang

notifications:
  email: ruan800@gmail.com

before_script:
  kerl list installations

otp_release:
    - 18.0
    - 18.1
    - 18.2
    - 18.2.1
    - 18.3
    - 19.0
    - 19.1
    - 19.2
    - 19.3

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

script:
  make && ./rebar3 clean && ./rebar3 compile && ./rebar3 eunit skip_deps=true && DEBUG=1 ./rebar3 coveralls send

env:
  global:
    - TIMEOUT=100

