language: erlang
notifications:
  email: ruan800@gmail.cmo
otp_release:
  - R16B
  - R15B01
  - R15B
  - R14B04
script: rebar compile && rebar skip_deps=true eunit && rebar skip_deps=true ct
env:
  global:
    - TIMEOUT=100
