language: erlang
notifications:
  email: ruan800@gmail.cmo
otp_release:
  - R15B03-1
  - R16B03-1
  - 17.3
  - 17.5
  - 18.0
  - 18.3
  - 19.0
script: rebar compile && rebar skip_deps=true eunit && rebar skip_deps=true ct
env:
  global:
    - TIMEOUT=100
