language: erlang
notifications:
  email: ruan800@gmail.com
before_script:
  kerl list installations
otp_release:
    - 17.0
    - 17.1
    - 17.3
    - 17.4
    - 17.5
    - 18.0
    - 18.1
    - 18.2
    - 18.2.1
    - 18.3
    - 19.0
    - 19.1
    - 19.2
    - 19.3

script:
  rebar clean && rebar compile && rebar skip_deps=true eunit && rebar skip_deps=true ct
env:
  global:
    - TIMEOUT=100

